fusioncenter/urls.py
from django.contrib import admin
from django.urls import path,include
from custom_user.views import HomeView,OwnerSignupView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('custom_user.urls')),
    path('', include('institution.urls')),
    path('', include('activity.urls')),
    path('', include('plans.urls')),

    path('', HomeView.as_view(), name='home'), 
    path('owner_signup/', OwnerSignupView.as_view(), name='owner_signup'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plans/urls.py
# plans/urls.py
from django.urls import path
from .views import (

    PlanListView, CreatePlanView, EditPlanView, 
    PlanDetailView, CreatePlanPricingView, EditPlanPricingView, PlanPricingDetailView,
    AssignUserPlanView, EditUserPlanView, PlanPricingSessionListView,ParticipantPlanPricingSessionListView,
    
    ParticipantPlanListView, ParticipantPlanDetailView, ParticipantPlanPricingSessionsView,
    
    plan_info_htmx
)

urlpatterns = [
    path('plan/list/', PlanListView.as_view(), name='plan_list'),
    path('plan/create/<int:site_id>/', CreatePlanView.as_view(), name='create_plan'),
    path('plan/edit/<int:plan_id>/', EditPlanView.as_view(), name='edit_plan'),
    path('plan/detail/<int:plan_id>/', PlanDetailView.as_view(), name='plan_detail'),
    path('plan_pricing/create/<int:plan_id>/', CreatePlanPricingView.as_view(), name='create_plan_pricing'),
    # path('plan/<int:plan_id>/edit_pricing/<int:pricing_id>/', EditPlanPricingView.as_view(), name='edit_plan_pricing'),
    path('plan_pricing/detail/<int:plan_pricing_id>/', PlanPricingDetailView.as_view(), name='plan_pricing_detail'),
    path('user_plan/create/<int:pricing_id>/', AssignUserPlanView.as_view(), name='assign_user_plan'),
    path('user_plan/edit/<int:user_plan_id>/', EditUserPlanView.as_view(), name='edit_user_plan'),

    path('plan_pricing/session/list/<int:plan_pricing_id>/', PlanPricingSessionListView.as_view(), name='plan_pricing_session_list'),
    path('plan_pricing/participant_session/list/<int:user_plan_id>/', ParticipantPlanPricingSessionListView.as_view(), name='participant_plan_pricing_session_list'),

    # participant urls
    path('participant_plan/list/', ParticipantPlanListView.as_view(), name='participant_plan_list'),
    path('participant_plan/detail/<int:plan_id>/', ParticipantPlanDetailView.as_view(), name='participant_plan_detail'),
    path('participant_plan_pricing/session/list/<int:user_plan_id>/', ParticipantPlanPricingSessionsView.as_view(), name='participant_plan_pricing_sessions'),
    # path('plan_pricing_session_list/<int:plan_pricing_id>/', PlanPricingSessionListView.as_view(), name='plan_pricing_session_list'),
    
    # htmx
    path('plan_info_htmx/<int:plan_id>', plan_info_htmx, name='plan_info_htmx'),
    

]

plans/models.py
# plans.models

from django.db import models
from activity.models import Activity
from institution.models import Site
from custom_user.models import User

class Plan(models.Model):
    PLAN_TYPE_CHOICES = [
        ('limited', 'Limited'),
        ('unlimited', 'Unlimited'),
    ]

    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    ]

    name = models.CharField(max_length=255)
    plan_type = models.CharField(max_length=20, choices=PLAN_TYPE_CHOICES)
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active')
    activities = models.ManyToManyField(Activity, related_name='plans')

    def __str__(self):
        return self.name

class PlanPricing(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    ]

    PRICE_UNIT_CHOICES = [
        ('ARS', 'Argentine Peso'),
        ('USD', 'US Dollar'),
        ('EUR', 'Euro'),
    ]

    name = models.CharField(max_length=255)
    from_date = models.DateField()
    to_date = models.DateField()
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    sessions_quantity = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active')
    price_unit = models.CharField(max_length=50, choices=PRICE_UNIT_CHOICES)
    price_quantity = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.plan.name} - {self.name}"


class UserPlan(models.Model):

    PAYMENT_CHOICES = [
        ('unpaid', 'Unpaid'),
        ('cash', 'Cash'),
        ('bank_transfer', 'Bank Transfer'),
        ('credit', 'Credit Card'),
        ('debit', 'Debit Card'),
        ('mercado_pago', 'Mercado Pago'),
        ('paypal', 'PayPal'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plan_pricing = models.ForeignKey(PlanPricing, on_delete=models.CASCADE)
    sessions_left = models.PositiveIntegerField()
    payment_method = models.CharField(max_length=20, choices=PAYMENT_CHOICES, default='unpaid')
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_user_plans')

    def __str__(self):
        return f"{self.user.email} - {self.plan_pricing.plan.name}"
    
    def get_payment_method_display(self):
        return dict(self.PAYMENT_CHOICES).get(self.payment_method, self.payment_method)

plans/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Plan, PlanPricing, UserPlan
from institution.models import Institution, Site, Staff
from activity.models import Session, Participants
from .forms import CreatePlanForm, EditPlanForm, CreateUnlimitedPlanPricingForm, CreateLimitedPlanPricingForm, EditLimitedPlanPricingForm, EditUnlimitedPlanPricingForm, AssignUserPlanForm, EditUserPlanForm
from django.http import Http404
from custom_user.models import User
from django.contrib import messages
from django.db import models

from datetime import date

from django.db.models import F,Count,Q
from django.template.loader import render_to_string
from django.http import HttpResponse

from .utils.permissions_utils import (
    is_institution_owner, 
    is_institution_instructor, 
    is_institution_staff, 
    is_owner_of_site, 
    is_staff_responsible_for_site, 
    is_activity_of_owner_sites, 
    is_activity_of_staff_sites,
    is_session_of_owner_sites,
    is_session_of_staff_sites,
    is_owner_of_space,
    is_staff_responsible_for_space,
    is_instructor_of_session,
)

from django.views import View

class PlanListView(View):
    template_name = 'plan/plan_list.html'

    @classmethod
    def as_view(cls, **kwargs):
        view = super().as_view(**kwargs)
        return login_required(login_url='login')(user_passes_test(lambda u: is_institution_owner(u) or is_institution_staff(u), login_url='login')(view))

    def get(self, request, *args, **kwargs):
        plans_by_site = {}

        if is_institution_owner(request.user):
            # Get the institution owned by the current user
            institution = Institution.objects.get(owner=request.user)

            # Get the sites related to the institution
            sites = institution.sites.all().order_by('name')

            # Retrieve the plans associated with those sites and order them by site and plan name
            for site in sites:
                plans_by_site[site] = Plan.objects.filter(site=site).order_by('name')
        elif is_institution_staff(request.user):
            # For staff, list plans based on responsible sites
            staff_profile = Staff.objects.get(user=request.user)
            responsible_sites = staff_profile.responsible_sites.all()
            
            for site in responsible_sites:
                plans_by_site[site] = Plan.objects.filter(site=site).order_by('name')

        context = {
            'plans_by_site': plans_by_site,
        }

        # Render the plans in a template
        return render(request, self.template_name, context)
    
class CreatePlanView(View):
    template_name = 'plan/create_plan.html'

    @classmethod
    def as_view(cls, **kwargs):
        view = super().as_view(**kwargs)
        return login_required(login_url='login')(user_passes_test(lambda u: is_institution_owner(u) or is_institution_staff(u), login_url='login')(view))

    def get(self, request, site_id):
        site = get_object_or_404(Site, id=site_id)
        # Check if the user is the owner or a staff member responsible for the site
        if not (is_owner_of_site(request.user, site) or is_staff_responsible_for_site(request.user, site)):
            return render(request, 'permission_denied.html')
        form = CreatePlanForm(site=site)
        return render(request, self.template_name, {'form': form, 'site': site})

    def post(self, request, site_id):
        site = get_object_or_404(Site, id=site_id)
        # Check if the user is the owner or a staff member responsible for the site
        if not (is_owner_of_site(request.user, site) or is_staff_responsible_for_site(request.user, site)):
            return render(request, 'permission_denied.html')
        form = CreatePlanForm(request.POST, site=site)

        if form.is_valid():
            plan = form.save(commit=False)
            selected_activity_ids = request.POST.getlist('activities')
            form.set_activities(selected_activity_ids)
            plan.site = site
            form.save()
            return redirect('plan_list')

        return render(request, self.template_name, {'form': form, 'site': site})

class EditPlanView(View):

    template_name = 'plan/edit_plan.html'

    @classmethod
    def as_view(cls, **kwargs):
        view = super().as_view(**kwargs)
        return login_required(login_url='login')(user_passes_test(lambda u: is_institution_owner(u) or is_institution_staff(u), login_url='login')(view))

    def get(self, request, plan_id):
        plan = get_object_or_404(Plan, id=plan_id)

        site = plan.site
        # Check if the user is the owner or a staff member responsible for the site
        if not (is_owner_of_site(request.user, site) or is_staff_responsible_for_site(request.user, site)):
            return render(request, 'permission_denied.html')
        
        form = EditPlanForm(instance=plan, site=site)
        return render(request, self.template_name, {'form': form, 'site': site, 'plan': plan})

    def post(self, request, plan_id):
        plan = get_object_or_404(Plan, id=plan_id)

        # Check if the user is the owner
        if not is_institution_owner(request.user):
            return render(request, 'permission_denied.html')

        site = plan.site
        # Check if the user is the owner or a staff member responsible for the site
        if not (is_owner_of_site(request.user, site) or is_staff_responsible_for_site(request.user, site)):
            return render(request, 'permission_denied.html')
        
        form = EditPlanForm(request.POST, site=site, instance=plan)

        if form.is_valid():
            updated_plan = form.save(commit=False)
            selected_activity_ids = request.POST.getlist('activities')
            form.set_activities(selected_activity_ids)
            updated_plan.site = site
            form.save()
            return redirect('plan_list')

        return render(request, self.template_name, {'form': form, 'site': site, 'plan': plan})
    

class PlanDetailView(View):
    template_name = 'plan/plan_detail.html'

    @classmethod
    def as_view(cls, **kwargs):
        view = super().as_view(**kwargs)
        return login_required(login_url='login')(user_passes_test(lambda u: is_institution_owner(u) or is_institution_staff(u), login_url='login')(view))

    def get(self, request, plan_id):
        
        plan = get_object_or_404(Plan, id=plan_id)
        site = plan.site
        # Check if the user is the owner or a staff member responsible for the site
        if not (is_owner_of_site(request.user, site) or is_staff_responsible_for_site(request.user, site)):
            return render(request, 'permission_denied.html')
        
        context = {
            'plan': plan,
        }

        return render(request, self.template_name, context)

class CreatePlanPricingView(View):
    template_name = 'plan/create_plan_pricing.html'

    @classmethod
    def as_view(cls, **kwargs):
        view = super().as_view(**kwargs)
        return login_required(login_url='login')(user_passes_test(lambda u: is_institution_owner(u) or is_institution_staff(u), login_url='login')(view))

    def get(self, request, plan_id):
        plan = get_object_or_404(Plan, id=plan_id)

        site = plan.site
        # Check if the user is the owner or a staff member responsible for the site
        if not (is_owner_of_site(request.user, site) or is_staff_responsible_for_site(request.user, site)):
            return render(request, 'permission_denied.html')

        if plan.plan_type == 'unlimited':
            form = CreateUnlimitedPlanPricingForm()
        elif plan.plan_type == 'limited':
            form = CreateLimitedPlanPricingForm()

        context = {
            'form': form,
            'plan': plan,
        }

        return render(request, self.template_name, context)

    def post(self, request, plan_id):
        plan = get_object_or_404(Plan, id=plan_id)

        site = plan.site
        # Check if the user is the owner or a staff member responsible for the site
        if not (is_owner_of_site(request.user, site) or is_staff_responsible_for_site(request.user, site)):
            return render(request, 'permission_denied.html')

        if plan.plan_type == 'unlimited':
            form = CreateUnlimitedPlanPricingForm(request.POST)
        elif plan.plan_type == 'limited':
            form = CreateLimitedPlanPricingForm(request.POST)

        if form.is_valid():
            pricing = form.save(commit=False)
            
            # Set status as 'active' directly
            pricing.status = 'active'

            # If the plan is unlimited, exclude sessions_quantity field
            if plan.plan_type == 'unlimited':
                pricing.sessions_quantity = 0

            pricing.plan = plan
            form.save()
            return redirect('plan_detail', plan_id=plan.id)

        context = {
            'form': form,
            'plan': plan,
        }

        return render(request, self.template_name, context)

class EditPlanPricingView(View):
    template_name = 'plan/edit_plan_pricing.html'

    @classmethod
    def as_view(cls, **kwargs):
        view = super().as_view(**kwargs)
        return login_required(login_url='login')(user_passes_test(lambda u: is_institution_owner(u) or is_institution_staff(u), login_url='login')(view))

    def get(self, request, plan_id, pricing_id):
        plan = get_object_or_404(Plan, id=plan_id)
        site = plan.site
        # Check if the user is the owner or a staff member responsible for the site
        if not (is_owner_of_site(request.user, site) or is_staff_responsible_for_site(request.user, site)):
            return render(request, 'permission_denied.html')
        
        pricing = get_object_or_404(PlanPricing, id=pricing_id)

        # Check if the user is the owner

templates/plan/assign_user_plan.html
{% extends 'base.html' %}

{% block content %}

<div class="container mx-auto pt-4 pl-6 pr-6 pb-6 text-center">
    <h3 class="text-2xl mx-auto mb-2 font-bold text-white">Assign User to:</h3>
    <p class="text-lg mx-auto mb-4 font-bold text-white">"{{ pricing.name }} | {{ pricing.plan.name }}"</p>
    <form method="post" enctype="multipart/form-data" class="md:w-1/2 mx-auto">
        {% csrf_token %}

        <div class="grid grid-cols-1 gap-4 mb-4">
            <div>
                <label for="{{ form.email.id_for_label }}" class="block mb-2 text-left text-sm font-medium text-white">User Email</label>
                <input
                autofocus
                    type="email"
                    name="{{ form.email.name }}"
                    maxlength="255"
                    id="{{ form.email.auto_id }}"
                    value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                    class="w-full px-3 py-2 text-sm text-white bg-gray-700
                    {% if form.email.errors %}
                    border-red-500
                    {% else %}
                    border-gray-600
                    {% endif %} rounded-lg focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:ring-offset-gray-900 border-gray-600 placeholder-gray-400"
                >
                {% if form.email.errors %}
                <div class="mt-2 text-sm text-left text-red-500">{{ form.email.errors }}</div>
                {% endif %}
            </div>
            <div>
                <label for="{{ form.payment_method.id_for_label }}" class="text-left block mb-2 text-sm font-medium text-gray-900 text-white">
                    {{ form.payment_method.label }}
                </label>
                <select name="{{ form.payment_method.name }}" id="{{ form.payment_method.id_for_label }}"
                        class="w-full px-3 py-2 text-sm text-white bg-gray-700
                               {% if form.payment_method.errors %}
                                   border-red-500
                               {% else %}
                                   border-gray-600
                               {% endif %}
                               rounded-lg focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:ring-offset-gray-900 border-gray-600 placeholder-gray-400">
                    <option value="" {% if not form.payment_method.value %}selected{% endif %}>Select Payment Method</option>
                    {% for key, value in form.payment_method.field.choices %}
                        <option value="{{ key }}" {% if key == form.payment_method.value %}selected{% endif %}>
                            {{ value }}
                        </option>
                    {% endfor %}
                </select>
                {% if form.payment_method.errors %}
                    <div class="mt-2 text-sm text-left text-red-500">{{ form.payment_method.errors }}</div>
                {% endif %}
            </div>
            
        </div>

        <div id="action_buttons" class="text-center mx-auto mt-8 flex justify-center space-x-4">
            <a href="{% url 'plan_pricing_detail' pricing.id %}" class="flex-1 px-4 py-2 text-red-500 hover:text-red-700 text-sm font-medium border border-red-500 rounded-lg text-center sm:w-auto">Cancel</a>
            <button type="submit" class="flex-1 px-4 py-2 text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-800 font-medium rounded-lg text-sm sm:w-auto">Save</button>
        </div>
        
    </form>
</div>

{% endblock %}

templates/plan/plan_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="md:mx-24 md:pt-2 pt-2 mx-2">

    <div class="flex items-center mt-2">
        <a href="{% url 'plan_list' %}" class="text-blue-500 hover:underline">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
            </svg>
        </a>
        <h3 class="text-2xl font-bold text-white overflow-hidden whitespace-nowrap max-w-[30ch] overflow-ellipsis ml-2">
            {{ plan.name }}
        </h3>
        <h2 class="text-md text-white overflow-hidden whitespace-nowrap max-w-[20ch] inline overflow-ellipsis ml-auto">
            <span class="hidden lg:inline">Type:</span> 
            <span class="font-thin hidden lg:inline">{{ plan.plan_type|capfirst }}</span>
        </h2>
        
        
        <h2 class="text-md text-white overflow-hidden hidden lg:inline whitespace-nowrap max-w-[20ch] inline overflow-ellipsis ml-8">
            <span class="">Status:</span> 
            <span class="mt-1 w-3 h-3  {% if plan.status == 'active' %}bg-green-500{% else %}bg-red-500{% endif %} rounded-full hidden md:inline-block"></span>
            <span class="font-thin">{{ plan.status|capfirst }}</span>
        </h2>
        <button data-modal-target="small-modal" data-modal-toggle="small-modal" class="hidden lg:inline block ml-8 w-full md:w-auto text-white focus:ring-4 focus:outline-none  font-medium rounded-lg text-sm px-5 py-2.5 text-center bg-gray-600 hover:bg-gray-700 focus:ring-gray-800" type="button">
            Activities
        </button>
        <div id="small-modal" tabindex="-1" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
            <div class="relative w-full max-w-md max-h-full">
                <!-- Modal content -->
                <div class="relative rounded-lg shadow bg-gray-700">
                    <!-- Modal header -->
                    <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t border-gray-600">
                        <h3 class="text-xl font-medium text-white">
                            Plan Activity List
                        </h3>
                        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center hover:bg-gray-600 hover:text-white" data-modal-hide="small-modal">
                            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                            </svg>
                            <span class="sr-only">Close modal</span>
                        </button>
                    </div>
                    <!-- Modal body -->
                    <div class="p-4 md:p-5 space-y-4">
                        
                        {% for activity in plan.activities.all %}
                        <div>
                            <a href="{% url 'activity_detail' activity.id %}" class="underline text-base leading-relaxed text-gray-400">
                                {{ activity.name }}
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h3 class="text-md font-thin text-white overflow-hidden whitespace-nowrap max-w-[30ch] overflow-ellipsis ml-10">
        {{ plan.site.name }}
    </h3>
    <div class="flex items-center mt-2 mb-4">
        <h3 class="text-xl font-bold text-white overflow-hidden whitespace-nowrap max-w-[20ch] overflow-ellipsis ml-2">
            Plan Pricing List
        </h3>
        <a href="{% url 'create_plan_pricing' plan.id %}"" class="flex items-center focus:outline-none text-white bg-green-600 hover:bg-green-700 focus:ring-4 focus:outline-none focus:ring-green-800 ml-auto font-medium rounded-lg text-sm px-2 py-2 text-center" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>
            <span class="hidden lg:inline mx-2">Plan Pricing</span>
        </a>
    </div>
    
    {% if plan.planpricing_set.all %}
    <div class="relative overflow-x-auto shadow-md rounded-lg bg-gray-700 ">
        <table class="w-full text-sm text-left text-gray-400">
            <thead class="text-xs uppercase bg-gray-600 text-gray-400">
                <tr>
                    <th scope="col" class="text-white px-3 py-3">
                        Name
                    </th>
                    <th scope="col" class="text-white text-center px-3 py-3 hidden md:table-cell">
                        From
                    </th>
                    <th scope="col" class="text-white text-center px-3 py-3 hidden md:table-cell">
                        To
                    </th>

                    {% if plan.plan_type == 'limited' %}
                    <th scope="col" class="text-white text-center px-3 py-3 hidden md:table-cell">
                        Quantity
                    </th>
                    {% endif %}
                    <th scope="col" class="text-white text-center px-3 py-3 hidden md:table-cell">
                        Price
                    </th>
                    <th scope="col" class="text-white text-right px-3 py-3 ">
                        Actions
                    </th>
                    <!-- Add more columns as needed -->
                </tr>
            </thead>
            <tbody>
                {% for pricing in plan.planpricing_set.all|dictsort:"from_date" %}
                    <tr class="bg-gray-700 border-gray-700 hover:bg-gray-600">
                        <td class="px-3 py-4 whitespace-nowrap text-gray-300">
                            {{ pricing.name }}
                        </td>
                        
                        <td class="px-3 py-4 text-center hidden md:table-cell">
                            {{ pricing.from_date|date:"D d M y" }}
                        </td>
                        <td class="px-3 py-4 text-center hidden md:table-cell">
                            {{ pricing.to_date|date:"D d M y" }}
                        </td>
                        

                        {% if plan.plan_type == 'limited' %}
                        <td class="px-6 py-4 text-center hidden md:table-cell">
                            {{ pricing.sessions_quantity }}
                        </td>
                        {% endif %}

                        <td class="px-6 py-4 text-center hidden md:table-cell">
                            {{ pricing.price_unit }} {{ pricing.price_quantity }}
                        </td>
                        <td class="px-3 py-4 text-right">
                            <div class="flex justify-end items-center">

                                <a href="{% url 'assign_user_plan' pricing.id %}" class="ml-2 text-green-500 hover:underline">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                                      </svg>
                                      
                                </a>
                                <a href="{% url 'plan_pricing_session_list' pricing.id %}" class="ml-2 text-yellow-500 text-center hover:underline">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zM3.75 12h.007v.008H3.75V12zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm-.375 5.25h.007v.008H3.75v-.008zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
                                      </svg>
                                </a>
                                <a href="{% url 'plan_pricing_detail' plan_pricing_id=pricing.id %}" class="ml-2 text-gray-300 hover:underline">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
                                  </svg>
                                  
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <h5 class="text-xl ml-2 mt-2 text-white">No pricing created for this plan. Please add a new plan pricing.</h5>
    {% endif %}

</div>

{% endblock %}